### PR TITLE
update groupme message format for clarity

### PR DESCRIPTION
**Pull request by weallwegot**

### CODE REVIEW

**Comment by weallwegot** [comment]
Any thoughts on this update?

**Comment by eviltrout** [comment]
Can you explain why you made this change and what it helps with? 

Maybe a screenshot of before/after would help us understand.

**Comment by weallwegot** [comment]
yea, sure, i originally wrote the groupme integration without much attention paid to how the format of messages gets populated in the chat app. 
This change just makes it a bit more clear what is happening when the message comes in. GroupMe doesn't do hyperlinking for instance, so just re-arranged things, and spaced it out so its easier to understand, heres an example:


Original:

Test User @test-user: Test Topic Title({Domain-URL}/t/example-topic/43/3) [Category] tag1, tag2, tag3, tag4 - is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the releas...

New Format:

Test User 
@test-user Posted to {Discourse Site Name}

Topic: Test Topic Title [Category]

is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the releas...

(Read More: {Domain-URL}/t/example-topic/43/3)

**Comment by eviltrout** [comment]
Great, thank you for the context. I've merged it now! Thanks for the patch.

**Pull request merged**
