### PR TITLE
Fix HipChat WebHook URL validation

### PR DESCRIPTION
**Pull request by rohitsden**
Submitting a pull request as discussed over at: 
https://meta.discourse.org/t/hipchat-integration/77883

This is my first attempt at a pull request, so please let me know if you need me to add anything more to this. :)

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
I just had a look here: https://confluence.atlassian.com/hc/configuring-hipchat-server-608731851.html

I think that a hipchat server can be any domain name or IP address, it doesn't need to contain `hipchat.`. So I think the easiest thing is to make the regex `^\S+$` (i.e. allow anything that isn't whitespace). The error handling should report any issues with invalid URLs to the user when they click the "test" button.

**Comment by rohitathworks** [comment]
@davidtaylorhq - Update the PR based on your recommendation.

**Comment by davidtaylorhq** [comment]
Looks good to me, we’ll need one of the team to merge it in.

@tgxworld please can you review this? :)

**Comment by SamSaffron** [comment]
OK merging! thanks

**Pull request merged**
