### PR TITLE
GroupMe added as Provider

### PR DESCRIPTION
**Pull request by weallwegot**
added groupme as a provider. 

uses [group me bots](https://dev.groupme.com/docs/v3#bots_post) as posters instead of developer access tokens directly. 

only thing different than others is the option to send to multiple groups simultaneously. 
GroupMe doesn't have the "channel" concept really, but in the future I could treat each group chat as a separate "channel"

other future functionality would be using the image service to include attachments to posts.

### CODE REVIEW

**Comment by weallwegot** [comment]
Actually I have a question about the `CHANNEL_PARAMETERS` list. I know you can make the regex validate a certain set of words but is it possible to have it be a dynamically populated dropdown? I want to use the channels to send to different Groupme chat rooms/instances. But currently the way to do that would be to enter in the bot_id (essentially a token required for posting) that corresponds to the Groupme instance. 
For ease of use itd be easiest to map the Bot IDs to GroupMe names. but those would both have to come from site settings. 

If i could make the channel selection be a dropdown then id be interested in dynamically populating it with the GroupMe instance names since those are more human-readable than an api token (the bot id).

**Comment by weallwegot** [comment]
made one last change to change the specification of channels from using IDs/tokens to groupme names so its now like this:

groupme-instance-names

**Comment by eviltrout** [comment]
Hi there! This PR looks solid to me. However the linting seems to be failing in CI. Could you look into that?

**Comment by weallwegot** [comment]
> Hi there! This PR looks solid to me. However the linting seems to be failing in CI. Could you look into that?

great thanks, ok i think i got the lint issues fixed

**Comment by eviltrout** [comment]
Thanks, let's try it out.

**Pull request merged**
